### ISSUE TITLE
[ClickTPA] %target％がプレイヤー名にならない

### ISSUE THREAD

**Issue by Megumiso** [GiganticMinecraft/SeichiAssist-ExternalLib#1]
https://discordapp.com/channels/237758724121427969/573131925158494220/765211368785051660

相手がtpaを拒否している場合に表示されるメッセージで起こる。

**Comment by unchama** [comment]
good first issue🎉

**Comment by Megumiso** [comment]
これいっその事 %target% の部分消してそれっぽいメッセージにしちゃえ！と思ってるんですがどう思いますか

**Comment by unchama** [comment]
はい　全然アリです😇

**Comment by Megumiso** [comment]
fixed.
