### ISSUE TITLE
ものくらふとを追加する

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist-ExternalLib#18]
現在seichi.click networkへの投票はJapan Minecraft Servers、minecraftserver.orgから投票できるが、これに加えてものくらふと( https://monocraft.net )からも投票できるようする。
JMSが長期的に止まっている為の代替手段の意味合いが強いが、JMS復活後もそのままにしておく予定。

**Comment by unchama** [comment]
minecraftserver.org は現在停止中
https://discord.com/channels/237758724121427969/237761024659423234/797478105508741131

**Comment by KisaragiEffective** [comment]
https://discord.com/channels/237758724121427969/959298142308814898/1030495793536307201 によりクローズ
