### ISSUE TITLE
[Dynmap] 地下に行ったプレイヤーがマップに表示されなくなる

### ISSUE THREAD

**Issue by Megumiso** [GiganticMinecraft/SeichiAssist-ExternalLib#19]
https://discordapp.com/channels/237758724121427969/573131925158494220/771997248724271114
参照：https://red.minecraftserver.jp/issues/8535

**Comment by Megumiso** [comment]
バグかと思ったけどアイデア会議行きっぽいのでいったん保留。

**Comment by Lucky3028** [comment]
承認された。
これか
https://github.com/webbukkit/dynmap/blob/87b57d56398f38e35912ba9db53291d5500fd4fb/spigot/src/main/resources/configuration.txt#L64
ここらへんと思われる
https://github.com/webbukkit/dynmap/blob/87b57d56398f38e35912ba9db53291d5500fd4fb/spigot/src/main/resources/configuration.txt#L66

**Comment by Megumiso** [comment]
設定変更済み。 次回再起動時に反映。
```
    hideifshadow: -1
    hideifundercover: -1
```
