### ISSUE TITLE
本リポジトリの運用方針決定

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist-ExternalLib#2]
- 外部に公開すると非常に困る情報(致命的な不具合、非公開のIPアドレス,認証情報,APIKey、他運営チームがそのように判断した情報)は本リポジトリで公開/管理しない。
- 上記に当てはまらない情報で、特にオープン化された開発コミュニティの活動を行う上で必要となる情報(導入済み外部プラグインの名称,バージョン,config、SeichiAssistスコープ外の不具合,課題,新機能に関するissueなど)は、本リポジトリで公開/管理する。

他に意見あれば是非

**Comment by Lucky3028** [comment]
issueとかPRの分類に関して、各プラグインについての詳細な話(要は不具合や新機能といった、通常はそれ単体でissueとされるような事柄)を同じリポジトリで管理する以上、#1 のようなタイトルで人力でプラグイン名を書いておくだけでなく、ラベルなりプロジェクト機能なりでしっかりとした分類をできるようにするべきではないでしょうか。

**Comment by unchama** [comment]
@Lucky3028 そうですね。ラベルとプロジェクトだったらどっちが管理しやすいんだろう？

**Comment by Lucky3028** [comment]
@unchama 
ラベルのほうがissueにもPRにも直接結び付けられるので見やすそうみたいな適当な感覚があります（プロジェクト機能まったくわからない）

**Comment by unchama** [comment]
OK じゃあラベルにしましょう
別途、各外部プラグインのドキュメントを作りましょうか
plugins/<PluginName>/README.md に説明、バージョン情報、DLリンク、関連リンクなどを掲載するのはどうですか

**Comment by Lucky3028** [comment]
plugins直下に[プラグイン名].mdではだめなんです？他に何かファイル等アップロードすることあります？ymlとか？

**Comment by Lucky3028** [comment]
なるほど、そういうことならいいと思います

**Comment by unchama** [comment]
はい　ここまでの議論内容を README.mdに置いてクローズします

**Comment by Lucky3028** [comment]
@unchama 
やっぱりラベルではなくプロジェクト機能にしませんか？
もともと設定してあるラベルを消すのがなんか忍びないと言うか、そのまま使えるので消したくないと言うか

**Comment by unchama** [comment]
オッイイですよ　その方向にしましょう　バージョンアップ検証なんかもプロジェクトで管理するほうが都合が良さそうですね

**Comment by Lucky3028** [comment]
わーい
