### ISSUE TITLE
[WorldGuard] WorldGuardのフラグをいくつか解放する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist-ExternalLib#22]

**Comment by KisaragiEffective** [comment]
- [ ] `weather-lock`
-- 領域内で天候を固定
- [ ] `greeting`
-- 領域内に入ったときにメッセージを流す
- [ ] `farewell`
-- 領域外に出たときにメッセージを流す
- [ ] `snow-melt`
-- 雪が溶けるかどうか
- [ ] `ice-melt`
-- 氷が溶けるかどうか
建築権限を細かく設定する用 (?)
- [ ] `build`
-- 建築できるか
- [ ] `ride`
-- 乗り物に乗れるかどうか
- [ ] `sleep`
-- ベッドで眠れるかどうか (?)
- [ ] `water-flow`
-- 水が流れるかどうか
- [ ] `lava-flow`
-- 溶岩が流れるかどうか
- [ ] `mushroom-growth`
-- キノコが育つかどうか
- [ ] `grass-growth`
-- 草ブロックが伝播するかどうか
- [ ] `mycelium-spread`
-- 菌糸ブロックが伝播するかどうか
- [ ] `vine-growth`
-- ツタが伸びるかどうか
- [ ] `soil-dry`
-- 耕地が乾くかどうか
- [ ] `time-lock`
-- 時間を固定
- [ ] `teleport`
-- `/rg teleport <id>` でテレポートする場所の設定

**Comment by Megumiso** [comment]
buildは誰でも建築可能は流石にやばそう(間違ってチェック入れちゃったけど無視で)

**Comment by Lucky3028** [comment]
フラグの設定ミスは自己責任なので別にいいのでは？需要はなさそうですが...

**Comment by Lucky3028** [comment]
それ以外のやつは解放してもいいんじゃないでしょうか！

**Comment by Lucky3028** [comment]
`The fire-spread, water-flow and liquid-flow flags ... This is because these events can be very frequent, requiring more region lookups, and potentially slowing down your server (or at least warming the server room a bit more).` とも書いてあったんですが、現状って保護内で水とか溶岩は流れるんでしたっけ？

**Comment by KisaragiEffective** [comment]
:heavy_check_mark: The change has launched.

**Comment by Megumiso** [comment]
チェック済みのは本番反映済み。
