### ISSUE TITLE
[Spigot]Minecraftのバージョンが古すぎます。1.10.2で接続してください

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist-ExternalLib#3]
古いのは貴様だ
正しくは1.12.2
https://discord.com/channels/237758724121427969/237758724121427969/766594038143909929

**Comment by Megumiso** [comment]
これLobby鯖は spigot 1.10.2.jarで起動してるのでこうなってますね。
解決策としては、
1. jarを1.12.2に変更する
2. spigot.ymlのメッセージを強制的に1.12.2にする

**Comment by Lucky3028** [comment]
修正されていた
