### ISSUE TITLE
[GiganticGift] 現状使用できないので消す

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist-ExternalLib#34]
SeichiAssistがリファクタリングを開始する前（書かれたのは2018/4/28、29のニコニコ超会議の前と思われる）のプラグインであるため、連携するコマンドが変更されていてすでに利用できない。
したがって、このプラグインを消すか書き直す必要がある。ただし、ソースコードは存在しない。
製作者はMonchiさんと思われる。

**Comment by KisaragiEffective** [comment]
どんなコマンドを実行してたのでしょうか

**Comment by Lucky3028** [comment]
「/unlockachv <Achivement_No> <playername> give」です

**Comment by Lucky3028** [comment]
特に使用する予定はないので消しましょう

**Comment by Lucky3028** [comment]
see #9
