### ISSUE TITLE
[Bungee] MOTDの誤字 

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist-ExternalLib#37]
pickale -> pickaxe

**Comment by Megumiso** [comment]
それ今までずっとMOTDがpickaxeだと表示しきれないから略してたのかと思ってたんですけど、違うんです？

**Comment by Lucky3028** [comment]
こちらをどうぞ
https://red.minecraftserver.jp/issues/5119

**Comment by Lucky3028** [comment]
別issue参照。
