### ISSUE TITLE
ConfirmWhirlwindの設定をする

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist-ExternalLib#43]
/payを行うとき（誰かにmineを渡すとき）に、もう一度/payを打つなどの確認手段を作る

第7回アイデア会議にて承認された
https://redmine.seichi.click/issues/9205

**Comment by kory33** [comment]
> こちら、任意のコマンドを実行する際に再度コマンドの実行を要求するプラグインを書いたので良ければどうぞ。
> https://github.com/SigureRuri/ConfirmWhirlwind
> config.ymlに以下のように書くことで動作すると思います。
> ```
> commands-to-confirm:
>   - "pay \\w{1,16} \\d+"
> ```

これ良さそうです

**Comment by Lucky3028** [comment]
導入された
未設定

**Comment by Lucky3028** [comment]
設定を行った
