### ISSUE TITLE
スペクテイターを管理するプラグインを導入する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist-ExternalLib#70]
要件
* [x] 整地ワールドでのみスペクテイター許可
* [x] 特定の位置でのみスペクテイターON・OFFができるようにする
  * 例
    * スポーン地点でのみスペクテイターコマンドが有効
    * スペクテイターの付与/解除のコマブロを設置し、保護メンバーに追加する(コマンドでの実行権限は無し)
    * スペクテイターを解除するとスペクテイターになったときの場所に戻る
* [x] スペクテイターになれる時間を制限する
* [x] 時間が切れたあと次になれるまでのクールタイム

**Comment by KisaragiEffective** [comment]
https://github.com/SigureRuri/SpectatorTheater

全部満たしてそう

**Comment by Lucky3028** [comment]
実装された
