### ISSUE TITLE
[PermissionsEX]代替プラグインに入替

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/SeichiAssist-ExternalLib#8]
権限管理に使用しているが、だいぶ前からメンテされてないので、別プラグインへの切り替えを検討,実施する。
LuckPermあたりが有力？管理負荷の都合上、DBやシンボリックリンクなどで複数サーバー間で権限定義が同期可能なものが望ましい

**Comment by Lucky3028** [comment]
入れ替え時の手順
https://luckperms.net/wiki/Migration#the-process

- [ ] LuckPerms入れる
- [ ] マイグレーションプラグイン入れる
- [ ] 再起動する
- [ ] マイグレーションコマンド走らせる
- [ ] 止める
- [ ] PEXとマイグレーションプラグイン抜く
- [ ] 起動する

**Comment by Lucky3028** [comment]
eventサーバーで試したところ正常に作動した

**Comment by Lucky3028** [comment]
すべてのサーバーで入れ替えが完了した
